users:
  - name: tomas
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
    cookies:
      xf_session: "abcdef00000000000000000000000000"
      xf_tfa_trust: "asdgdfhkuo253qz-"
#    proxy_pool:
#      - "https://log:pass@127.0.0.10:8081"
#      - "socks5://log:pass@10.0.0.1:9050"
#  - name: petr
#    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
#    cookies:
#      xf_session: "abcdef00000000000000000000000001"

# 0 = no proxy, 1 = tor, 2 = proxy pool
proxy_type: 1
lolz_domain: "zelenka.guru"
found_count: 8
low_time: 5
high_time: 20
switch_time: 3
solve_time: 3
anti_captcha_key: "00000000000000000000000000000000"
site_key: "0x4AAAAAAADMHhlDN2zO9nrC"
send_referral_to_creator: true
